"""Builds the prompt for each task within the model's context budget."""

from __future__ import annotations

from typing import Any

from ..agents.base import COMMON_PRINCIPLES, AgentSpec, PluginSpec, Preparation
from ..knowledge.store import knowledge_base
from ..multimodal.documents import chunk_text
from ..multimodal.language import Language, response_instruction

CHARS_PER_TOKEN = 3.0


def _trim(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return text[: max(limit - 1, 0)].rsplit(" ", 1)[0] + "…"


def budgets(num_ctx: int, num_predict: int) -> dict[str, int]:
    total = int(num_ctx * CHARS_PER_TOKEN)
    reserve = int(min(num_predict, num_ctx // 3) * CHARS_PER_TOKEN)
    available = max(total - reserve - 2500, 2500)  # 2500 ≈ system prompt + request
    return {
        "history": int(available * 0.2),
        "attachments": int(available * 0.35),
        "sources": int(available * 0.35),
        "tools": int(available * 0.1),
    }


def history_messages(history: list[dict[str, Any]], budget: int) -> list[dict[str, str]]:
    out: list[dict[str, str]] = []
    used = 0
    for msg in reversed(history[-8:]):
        role = msg.get("role")
        content = str(msg.get("content") or "").strip()
        if role not in {"user", "assistant"} or not content:
            continue
        piece = _trim(content, max(budget // 3, 400))
        if used + len(piece) > budget:
            break
        out.append({"role": role, "content": piece})
        used += len(piece)
    return list(reversed(out))


def attachment_block(attachments: list[dict[str, Any]], query: str, budget: int) -> str:
    if not attachments:
        return ""
    per = max(budget // len(attachments), 600)
    parts = []
    for att in attachments:
        text = att.get("text") or ""
        label = f"{att.get('name', 'attachment')}"
        if att.get("kind") == "image":
            header = f"Image '{label}' — description generated by the local vision model {att.get('model', '')}:"
        else:
            header = f"Document '{label}':"
        if len(text) <= per:
            body = text
        else:
            chunks = chunk_text(text, target=700, overlap=80)
            order = knowledge_base.search_chunks(query, chunks, k=8)
            picked, used = [], 0
            for i in sorted(order[:8]):  # keep document order for readability
                c = chunks[i]["text"]
                if used + len(c) > per:
                    continue
                picked.append(c)
                used += len(c)
            if not picked:
                picked = [text[:per]]
            body = "Relevant excerpts:\n" + "\n…\n".join(picked)
        parts.append(f"{header}\n{body}")
    return "Attached by the user:\n\n" + "\n\n---\n\n".join(parts)


def sources_block(sources: list[dict[str, Any]], budget: int) -> str:
    if not sources:
        return ""
    per = max(budget // len(sources), 350)
    lines = ["Numbered sources (cite as [n] when you use them):"]
    for i, s in enumerate(sources, 1):
        origin = "Literature (Europe PMC)" if s.get("kind") == "literature" else f"NEXGRAFT knowledge base: {s.get('collection')}"
        lines.append(f"[{i}] {origin}\n{_trim(s.get('_text') or s.get('snippet') or '', per)}")
    return "\n\n".join(lines)


def build_task_messages(
    *,
    spec: AgentSpec,
    plugin: PluginSpec | None,
    task: dict[str, Any],
    all_tasks: list[dict[str, Any]],
    message: str,
    history: list[dict[str, Any]],
    attachments: list[dict[str, Any]],
    prep: Preparation,
    language: Language,
    num_ctx: int,
    num_predict: int,
) -> list[dict[str, str]]:
    b = budgets(num_ctx, num_predict)
    system_parts = [COMMON_PRINCIPLES, spec.system_prompt]
    if plugin:
        system_parts.append(plugin.prompt)
    system_parts.append(response_instruction(language))
    messages = [{"role": "system", "content": "\n\n".join(system_parts)}]
    messages.extend(history_messages(history, b["history"]))

    query = f"{task.get('instruction', '')}\n{message}"
    context_parts = []
    att = attachment_block(attachments, query, b["attachments"])
    if att:
        context_parts.append(att)
    if prep.context_blocks:
        context_parts.append(_trim("\n\n".join(prep.context_blocks), b["tools"] + 400))
    src = sources_block(prep.sources, b["sources"])
    if src:
        context_parts.append(src)
    if prep.notes:
        context_parts.append("Notes: " + " ".join(prep.notes))

    others = [t for t in all_tasks if t is not task and t.get("agent") != spec.id]
    if others:
        other_desc = "; ".join(f"{t['title']}" for t in others)
        request = (
            f"Overall user request: {message}\n\n"
            f"Your part, as {spec.name}: {task['instruction']}\n\n"
            f"Other NEXGRAFT workspaces are handling: {other_desc}. Focus only on your part and keep it concise."
        )
    elif task.get("instruction") and task["instruction"].strip() != message.strip():
        request = f"User request: {message}\n\nFocus: {task['instruction']}"
    else:
        request = message
    user_content = "\n\n".join(context_parts + [request]) if context_parts else request
    messages.append({"role": "user", "content": user_content})
    return messages


def build_synthesis_messages(message: str, results: list[dict[str, Any]], language: Language, num_ctx: int) -> list[dict[str, str]]:
    per = max(int(num_ctx * CHARS_PER_TOKEN * 0.45) // max(len(results), 1), 500)
    system = (
        f"{COMMON_PRINCIPLES}\n\nYou are the NEXGRAFT orchestrator. Several specialist workspaces each answered one "
        "part of the user's request. Write a brief unified result using three Markdown sections titled exactly "
        "'## Unified summary', '## How the pieces fit' and '## Suggested next steps'. Under the first, write 3 to 5 "
        "sentences connecting the parts. Under the second, write short bullets naming each workspace's contribution. "
        "Under the third, write a numbered list of concrete actions the user controls. Do not repeat details already "
        "given and do not add new technical claims. Keep it under 250 words.\n\n"
        + response_instruction(language)
    )
    parts = [f"User request: {message}"]
    for r in results:
        parts.append(f"### {r['agent_name']} — {r['title']}\n{_trim(r.get('content', ''), per)}")
    return [{"role": "system", "content": system}, {"role": "user", "content": "\n\n".join(parts)}]
